services:
  postgres:
    container_name: postgres
    image: postgres:17.6
    restart: unless-stopped
    env_file: .env
    expose:
      - "5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: ${DOCKER_NETWORK_DB_IP}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file: .env
    ports:   # optional: only needed if you want to access pgAdmin from host browser
      - "8088:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      default:
        ipv4_address: ${DOCKER_NETWORK_PGADMIN_IP}

  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    env_file: .env
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - postgres
    networks:
      default:
        ipv4_address: ${DOCKER_NETWORK_API_IP}

  bff:
    build:
      context: ./bff
      dockerfile: Dockerfile
    container_name: bff
    restart: unless-stopped
    depends_on:
      - api
    env_file:
      - .env
    expose:
      - "80"
    networks:
      default:
        ipv4_address: ${DOCKER_NETWORK_BFF_IP}

  reverse-proxy:
    image: nginx:1.29.3
    container_name: reverse-proxy
    restart: unless-stopped
    depends_on:
      - bff
      - api
      - keycloak
    volumes:
      - ./nginx/config:/etc/nginx/conf.d/
      - ./nginx/log/:/var/log/nginx/
      - ./frontend/dist:/usr/share/nginx/html  # Vue dist folder
    ports:              # ONLY THINGS EXPOSED PUBLICLY
      - "80:80"
      # - "443:443"    # enable when you add SSL
    networks:
      default:
        ipv4_address: ${DOCKER_NETWORK_PROXY_IP}

  keycloak-db:
    image: postgres:17.6
    restart: unless-stopped
    container_name: keycloak-db
    env_file:
      - .keycloak.env
    volumes:
      - ./keycloak-db-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      default:
        ipv4_address: ${DOCKER_NETWORK_KEYCLOAKDB_IP}

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    restart: unless-stopped
    container_name: keycloak
    env_file:
      - .keycloak.env
    command: start --optimized --http-enabled=true --hostname=http://${KEYC_HOSTNAME}:80
    depends_on:
      - keycloak-db
    expose:
      - "8080"
    networks:
      default:
        ipv4_address: ${DOCKER_NETWORK_KEYCLOAK_IP}

networks:
  default:
    name: ${DOCKER_NETWORK}
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK_SUBNET}